//= require jquery
//= require jquery_ujs
//= require handlebars
//= require ember
//= require ember-data
//= require_self
//= require retros
//= require remarks
RemoteRetro = Ember.Application.create();
