common: &common
  adapter: postgresql
  username: retroapp
  host: localhost

development:
  <<: *common
  database: table_dev

test:
  <<: *common
  database: table_test
  allow_concurrency: true
  pool: 5
  min_messages: error

production:
  <<: *common
  database: table_prod
