common: &common
  adapter: postgresql
  username: retroapp
  host: localhost

development:
  <<: *common
  database: retro_development

test:
  <<: *common
  database: retro_test
  allow_concurrency: true
  pool: 5
  min_messages: error

production:
  <<: *common
  database: retro_production
