common: &common
  adapter: postgresql
  username: retroapp
  password: password # from psql setup, see Postgresql

development:
  <<: *common
  database: retro_development

test:
  <<: *common
  database: retro_test

production:
  <<: *common
  database: retro_production
