common: &common
  adapter: postgresql
  username: retroapp
  host: localhost

development:
  <<: *common
  database: retro_development

test:
  <<: *common
  database: retro_test

production:
  <<: *common
  database: retro_production
